version: '3.8'

services: 
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timeSheetDevOps
    ports:
      - "3307:3306"
    
  app:  
    container_name: timesheet
    image: "borjinisyrine/devops"
    restart: unless-stopped
    depends_on:
      - mysqldb
    ports:
      - 8089:8089
    environment: 
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/timeSheetDevOps?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto":"update",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5Dialect"
      }'